package dev.cursedmc.wij.api

import net.minecraft.util.Identifier

object WIJConstants {
	// TODO: see if these values can be generated by the gradle script
	const val MOD_ID = "worldinajar"

	fun id(path: String): Identifier = Identifier(MOD_ID, path)
}
