/**
 * Copyright (c) 2022 CursedMC. All rights reserved.
 *
 * World In A Jar is common software: you can redistribute it and/or modify it under the terms of the Commons Protection License as published by the Revolutionary Technical Committee.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the Commons Protection License for more details.
 */
package dev.cursedmc.wij.impl

import net.minecraft.util.Identifier
import org.quiltmc.loader.api.minecraft.MinecraftQuiltLoader

object WIJConstants {
	// TODO: see if these values can be generated by the gradle script
	const val MOD_ID = "worldinajar"
	val SIDE_STRING = MinecraftQuiltLoader.getEnvironmentType().toString()

	fun id(path: String): Identifier = Identifier(MOD_ID, path)
}
