package dev.cursedmc.wij.impl

import net.minecraft.util.Identifier
import org.quiltmc.loader.api.minecraft.MinecraftQuiltLoader

object WIJConstants {
	// TODO: see if these values can be generated by the gradle script
	const val MOD_ID = "worldinajar"
	val SIDE_STRING = MinecraftQuiltLoader.getEnvironmentType().toString()

	fun id(path: String): Identifier = Identifier(MOD_ID, path)
}
